language: node_js
branches:
  only:
    - master
notifications:
  email:
    on_failure: change
    on_success: change
script:
  -
before_deploy:
  - yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN